loaders=fabric,neoforge
ui_source=legacy,mc121
fabric_remap=true
java_version=21
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
minecraft_artifact_version=1.21.1
neo_form_version=1.21.1-20240808.144430
mixin_version=0.17.3+mixin.0.8.7
mixin_java_compatibility=JAVA_21
pack_format=34
fast_restart_mixins=, "FastRestartWindowMixin", "FastRestartMinecraftMixin"
cloth_config_version=15.0.140
common_cloth_artifact=cloth-config-neoforge
fabric_loader_version=0.16.14
fabric_loader_version_min=0.16.9
fabric_api_version=0.116.14+1.21.1
kotlin_loader_version=1.13.11+kotlin.2.3.21
modmenu_version=11.0.4
modmenu_coordinate=com.terraformersmc:modmenu
neoforge_version=21.1.243
neoforge_loader_version_range=[4,)
kotlin_for_forge_version=5.12.0
kotlin_for_forge_version_range=[5,)
