loaders=fabric,neoforge
ui_source=mc26,mc262
fabric_remap=false
java_version=25
minecraft_version=26.2
minecraft_version_range=[26.2,26.3)
minecraft_artifact_version=26.2
neo_form_version=26.2-2
mixin_version=0.17.3+mixin.0.8.7
mixin_java_compatibility=JAVA_25
pack_format=88
cloth_config_version=26.2.155
common_cloth_artifact=cloth-config
fabric_loader_version=0.19.3
fabric_loader_version_min=0.19.3
fabric_api_version=0.155.2+26.2
kotlin_loader_version=1.13.13+kotlin.2.4.10
modmenu_version=20.0.1
modmenu_coordinate=com.terraformersmc:modmenu
neoforge_version=26.2.0.32-beta
neoforge_loader_version_range=[4,)
kotlin_for_forge_version=6.3.0
kotlin_for_forge_version_range=[6,)
