org.gradle.jvmargs=-Xmx3G

mod_version=0.1.0
maven_group=com.github.fanziyun
archives_base_name=363updater-1.20.1-forge
java_version=17
minecraft_version=1.20.1
minecraft_version_range=[1.20.1]
mod_id=updater363
mod_name=363Updater
mod_author=xingguangcuican/xingguangcuican6666(Github)
mod_license=MIT
forge_version=1.20.1-47.4.0
forge_version_range=[47,)
forge_loader_version_range=[47,)
kotlin_for_forge_version=4.12.0
kotlin_for_forge_version_range=[4,)
cloth_config_version=11.1.136
mixin_java_compatibility=JAVA_17
pack_format=15
updater_target=1.20.1-forge
