modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/fanziyun/363updater/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_author}"
logoFile = "assets/${mod_id}/icon.png"
description = '''Download Modrinth modpack configuration updates with three-way merging.'''

[[mixins]]
config = "updater363.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "kotlinforforge"
type = "required"
versionRange = "${kotlin_for_forge_version_range}"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "cloth_config"
type = "required"
versionRange = "[${cloth_config_version},)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "changelog363"
type = "optional"
versionRange = "[1,)"
ordering = "AFTER"
side = "CLIENT"
